# A Dockerfile to build an OpenShift Jenkins Slave Agent.
# It's based on the OpenShift Base image and provides Python 2.

# The v3.9 digest...
FROM openshift/jenkins-slave-base-centos7@sha256:72703571ef822fcf9cfa3448f043485adde297bd811d13033492b90cdc1e22c3
MAINTAINER Alan Christie (alanbchristie)

RUN yum -y --enablerepo=extras install epel-release
RUN yum -y install python-pip
RUN pip install --upgrade pip

# We're root at this stage of the script.
# Back to the base-image user (we know this empirically).
USER 1001
WORKDIR ${HOME}
