# A Dockerfile to build an OpenShift Jenkins Slave Agent.
# It's based on the OpenShift Base image and provides Python 2.

# The v3.10 digest...
FROM openshift/jenkins-slave-base-centos7@sha256:4a133527bab58df4ee0df9786a0fb9b2a4d2c422a9cc5077bd1bdf4bf867594a
MAINTAINER Alan Christie (alanbchristie)

RUN yum -y --enablerepo=extras install epel-release
RUN yum -y install python-pip
RUN pip install --upgrade pip

# We're root at this stage of the script.
# Back to the base-image user (we know this empirically).
USER 1001
WORKDIR ${HOME}
