# A Dockerfile to build an OpenShift Jenkins Slave Agent.
# It's based on the OpenShift Base image.

# The v3.10 digest...
FROM openshift/jenkins-slave-base-centos7@sha256:4a133527bab58df4ee0df9786a0fb9b2a4d2c422a9cc5077bd1bdf4bf867594a
MAINTAINER Alan Christie (alanbchristie)

RUN yum -y install https://centos7.iuscommunity.org/ius-release.rpm
RUN yum -y install \
    python36u \
    python36u-pip \
    python36u-devel

# We're root at this stage of the script.
# Return to the underlying user id (1001).
USER 1001
WORKDIR ${HOME}
